#!/usr/bin/env python3
"""Generate paper-ready LaTeX tables from consolidated CSV outputs.

Outputs:
- report/tables_enhanced_main_results.tex  (single consolidated table; readable style)
- report/tables_statistical_significance.tex
"""

from __future__ import annotations

from pathlib import Path
import pandas as pd


def _load_summary(path: str) -> pd.DataFrame:
    df = pd.read_csv(path).copy()
    return df.sort_values(["f1", "auc"], ascending=False).reset_index(drop=True)


def _fmt(x: float) -> str:
    return f"{x:.3f}"


def _esc(s: str) -> str:
    return s.replace("_", r"\_")


def build_main_table() -> str:
    evons_fake = _load_summary("colab_no_embeddings/outputs/evons_disinformation_merged_summary.csv")
    evons_vir = _load_summary("colab_no_embeddings/outputs/evons_virality_merged_summary.csv")
    fnn_fake = _load_summary("colab_no_embeddings/outputs/fakenewsnet_disinformation_merged_summary.csv")
    fnn_vir = _load_summary("colab_no_embeddings/outputs/fakenewsnet_virality_merged_summary.csv")

    blocks = [
        ("EVONS -- Fake-news Detection", evons_fake),
        ("EVONS -- Virality Prediction", evons_vir),
        ("FakeNewsNet -- Fake-news Detection", fnn_fake),
        ("FakeNewsNet -- Virality Prediction", fnn_vir),
    ]

    lines = [
        "% Auto-generated by tools/generate_paper_tables.py",
        "% Readability-oriented format, similar to the original manuscript style.",
        "% Balanced accuracy is not included because it is unavailable in consolidated summary CSVs.",
        "",
        "\\begin{table*}[t]",
        "\\centering",
        "\\small",
        "\\caption{Performance comparison across datasets and tasks (10-fold CV means; readable manuscript format).}",
        "\\label{tab:readable-full-results}",
        "\\begin{tabular}{llccccc}",
        "\\toprule",
        "\\textbf{Dataset / Task} & \\textbf{Model} & \\textbf{Acc} & \\textbf{F1} & \\textbf{Prec} & \\textbf{Rec} & \\textbf{ROC-AUC} " + r"\\",
        "\\midrule",
    ]

    for section_name, df in blocks:
        lines.append(f"\\multicolumn{{7}}{{c}}{{\\textbf{{{section_name}}}}} " + r"\\")
        lines.append("\\midrule")

        best_model = df.iloc[0]["model"]
        for _, r in df.iterrows():
            model = _esc(r["model"])
            model_disp = f"\\textbf{{{model}}}" if r["model"] == best_model else model
            lines.append(
                f" & {model_disp} & {_fmt(r['accuracy'])} & {_fmt(r['f1'])} & {_fmt(r['precision'])} & {_fmt(r['recall'])} & {_fmt(r['auc'])} \\\\" 
            )
        lines.append("\\midrule")

    # replace last midrule with bottomrule
    if lines[-1] == "\\midrule":
        lines[-1] = "\\bottomrule"
    else:
        lines.append("\\bottomrule")

    lines += ["\\end{tabular}", "\\end{table*}", ""]
    return "\n".join(lines)


def build_significance_table(stats_csv: Path) -> str:
    stats = pd.read_csv(stats_csv)
    f1 = stats[stats["metric"] == "f1"].copy()

    rows = []
    for dataset, task in [
        ("evons", "disinformation"),
        ("evons", "virality"),
        ("fakenewsnet", "disinformation"),
        ("fakenewsnet", "virality"),
    ]:
        block = f1[(f1["dataset"] == dataset) & (f1["task"] == task)].copy()
        if block.empty:
            continue

        model_scores: dict[str, float] = {}
        for _, r in block.iterrows():
            a = r["model_a"]
            b = r["model_b"]
            d = r["mean_diff"]
            model_scores[a] = model_scores.get(a, 0.0) + d
            model_scores[b] = model_scores.get(b, 0.0) - d

        best = max(model_scores, key=model_scores.get)
        comp = block[(block["model_a"] == best) | (block["model_b"] == best)].copy()
        comp["opponent"] = comp.apply(
            lambda r: r["model_b"] if r["model_a"] == best else r["model_a"], axis=1
        )
        comp["diff_best_minus_opp"] = comp.apply(
            lambda r: r["mean_diff"] if r["model_a"] == best else -r["mean_diff"], axis=1
        )
        comp = comp.sort_values("diff_best_minus_opp", ascending=False).head(3)

        for _, r in comp.iterrows():
            if r["model_a"] == best:
                ci_low = r["ci_low"]
                ci_high = r["ci_high"]
                effect_size = r["effect_size"]
            else:
                ci_low = -r["ci_high"]
                ci_high = -r["ci_low"]
                effect_size = -r["effect_size"]
            rows.append(
                {
                    "dataset_task": f"{dataset}/{task}",
                    "best": best,
                    "opponent": r["opponent"],
                    "diff": r["diff_best_minus_opp"],
                    "ci": f"[{ci_low:.4f}, {ci_high:.4f}]",
                    "p_holm": r["p_value_holm"],
                    "sig": "yes" if bool(r["significant_holm_005"]) else "no",
                    "effect_size": effect_size,
                }
            )

    out = pd.DataFrame(rows)

    lines = [
        "% Auto-generated by tools/generate_paper_tables.py",
        "",
        "\\begin{table*}[t]",
        "\\centering",
        "\\small",
        "\\caption{Top pairwise F1 comparisons (best model vs strongest alternatives per dataset/task).}",
        "\\label{tab:stats-top-pairs}",
        "\\begin{tabular}{lllccccl}",
        "\\toprule",
        "Dataset/Task & Best & Compared to & $\\Delta$F1 & 95\\% CI & Holm-$p$ & Effect size & Sig. " + r"\\",
        "\\midrule",
    ]

    for _, r in out.iterrows():
        lines.append(
            f"{r['dataset_task']} & {_esc(r['best'])} & {_esc(r['opponent'])} & {r['diff']:.4f} & {r['ci']} & {r['p_holm']:.4f} & {r['effect_size']:.4f} & {r['sig']} \\\\"
        )

    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""])
    return "\n".join(lines)


def main() -> None:
    Path("report/tables_enhanced_main_results.tex").write_text(build_main_table() + "\n", encoding="utf-8")
    Path("report/tables_statistical_significance.tex").write_text(
        build_significance_table(Path("report/stats_current.csv")) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
